package com.example.shopapi.dto.payment;

import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PaymentVerificationRequest - Request DTO for verifying Razorpay payment
 *
 * WHY THESE FIELDS:
 * After user completes payment in Razorpay checkout modal, Razorpay returns:
 * - razorpay_order_id: The order ID we created earlier
 * - razorpay_payment_id: Unique payment ID generated by Razorpay
 * - razorpay_signature: HMAC-SHA256 signature for verification
 *
 * Frontend must send all three to backend for verification.
 * We verify: HMAC-SHA256(order_id + "|" + payment_id, secret) == signature
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PaymentVerificationRequest {

    @NotBlank(message = "Razorpay order ID is required")
    private String razorpayOrderId;

    @NotBlank(message = "Razorpay payment ID is required")
    private String razorpayPaymentId;

    @NotBlank(message = "Razorpay signature is required")
    private String razorpaySignature;
}

